### ISSUE TITLE
Error: command 'rls.applySuggestion' already exists

### ISSUE THREAD

**Issue by tanis2000** [rust-lang/rls-vscode#420]
Opening a simple project with VSCode leads to RLS staying in the `starting` state. Checking the console output leads to the following error:

```
[Error - 6:54:54 PM] Notify file events failed.
Error: command 'rls.applySuggestion' already exists
	at e.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:711:907)
	at Object.registerCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:785:949)
	at ExecuteCommandFeature.register (/Users/tanis/.vscode/extensions/rust-lang.rust-0.4.10/node_modules/vscode-languageclient/lib/client.js:1484:53)
	at ExecuteCommandFeature.initialize (/Users/tanis/.vscode/extensions/rust-lang.rust-0.4.10/node_modules/vscode-languageclient/lib/client.js:1474:14)
	at LanguageClient.initializeFeatures (/Users/tanis/.vscode/extensions/rust-lang.rust-0.4.10/node_modules/vscode-languageclient/lib/client.js:2151:21)
	at connection.initialize.then (/Users/tanis/.vscode/extensions/rust-lang.rust-0.4.10/node_modules/vscode-languageclient/lib/client.js:1871:18)
	at <anonymous>
```

The relevant VSCode configuration follows:

```
    "rust.mode": "rls",
    "rust.rustup": {
        "toolchain": "stable-x86_64-apple-darwin",
        "nightlyToolchain": "nightly-x86_64-apple-darwin",
    },
    "rust.rls": {
        "useRustfmt": true,
    },
    "rust.target_dir": "target/rls",
    "rust-client.channel": "nightly",
```

**Comment by Xanewok** [comment]
We don't ship this command anymore.
