### ISSUE TITLE
"find implementations failed: Error: An unknown error occurred"

### ISSUE THREAD

**Issue by samuela** [rust-lang/rls-vscode#437]
I just installed the RLS extension and opened up a brand new project: `cargo new asdf --bin`. Then opened up VSCode and ran "Rust: Find Implementations" which produced this error. There's no other error information in the UI.

In the dev console I see an error which may or may not be related:

```
Error: command 'rls.findImpls' already exists
	at e.registerCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:451:595)
	at Object.registerTextEditorCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:603:190)
	at ClientWorkspace.registerCommands (/Users/skainswo/.vscode-insiders/extensions/rust-lang.rust-0.4.10/out/src/extension.js:173:55)
	at ClientWorkspace.<anonymous> (/Users/skainswo/.vscode-insiders/extensions/rust-lang.rust-0.4.10/out/src/extension.js:165:18)
	at Generator.next (<anonymous>)
	at /Users/skainswo/.vscode-insiders/extensions/rust-lang.rust-0.4.10/out/src/extension.js:16:71
	at new Promise (<anonymous>)
	at __awaiter (/Users/skainswo/.vscode-insiders/extensions/rust-lang.rust-0.4.10/out/src/extension.js:12:12)
	at ClientWorkspace.start (/Users/skainswo/.vscode-insiders/extensions/rust-lang.rust-0.4.10/out/src/extension.js:131:16)
	at ClientWorkspace.<anonymous> (/Users/skainswo/.vscode-insiders/extensions/rust-lang.rust-0.4.10/out/src/extension.js:205:25)
	at Generator.next (<anonymous>)
	at fulfilled (/Users/skainswo/.vscode-insiders/extensions/rust-lang.rust-0.4.10/out/src/extension.js:13:58)
	at <anonymous>
t.onDidNotificationChange @ notificationsAlerts.ts:40
```

I'm using Version 1.28.0-insider (1.28.0-insider) (431ef9da3cf88a7e164f9d33bf62695e07c6c2a9) and extension version v0.4.10.

**Comment by samuela** [comment]
Also applies to Version 1.29.0-insider (1.29.0-insider) (9e017425b3d38cfc2d31a7375a28ff6d833ea4ae).

**Comment by Xanewok** [comment]
I agree the error should be more informative; I believe the result should be just empty.

Can you try running it on
```rust
trait Foo {} // On "Foo" identifier
struct Bar;
struct Baz;

impl Foo for Bar {}
impl Foo for Baz {}
```

and see if you're presented with both locations for `impl Foo for *Bar*` and `impl Foo for *Baz*`?

**Comment by samuela** [comment]
@Xanewok I ran it once (perhaps before RLS finished recompiling) and got the same error

<img width="506" alt="Screen Shot 2019-04-09 at 1 31 57 PM" src="https://user-images.githubusercontent.com/226872/55833130-e6e2e080-5acb-11e9-822c-ff1147e81a57.png">

Then running it again, it worked and presented both locations, Bar and Baz.
