### ISSUE TITLE
RLS crashes on `Canonicalizer::canonicalize`

### ISSUE THREAD

**Issue by 0x7CFE** [rust-lang/rls-vscode#462]
RLS crashed when I tried to open https://github.com/paritytech/substrate/commit/993026e0693899aeb5a55468032c7fc4eabd02e1 repo in VSCode. Both compiler and RLS were installed via rustup.

`rustc 1.32.0-nightly (0c999ed13 2018-12-03) running on x86_64-unknown-linux-gnu`

```
thread '<unnamed>' panicked at 'Box<Any>', src/librustc_errors/lib.rs:600:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:495
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::bug
   8: rustc::util::bug::opt_span_bug_fmt::{{closure}}
   9: rustc::ty::context::tls::with_opt::{{closure}}
  10: rustc::ty::context::tls::with_context_opt
  11: rustc::ty::context::tls::with_opt
  12: rustc::util::bug::opt_span_bug_fmt
  13: rustc::util::bug::bug_fmt
  14: rustc::infer::canonical::canonicalizer::Canonicalizer::canonicalize
  15: rustc::infer::canonical::query_response::<impl rustc::infer::InferCtxt<'cx, 'gcx, 'tcx>>::make_canonicalized_query_response
  16: rustc::ty::context::tls::with_related_context
  17: rustc::infer::canonical::query_response::<impl rustc::infer::InferCtxtBuilder<'cx, 'gcx, 'tcx>>::enter_canonical_trait_query
  18: rustc_traits::normalize_projection_ty::normalize_projection_ty
  19: rustc::ty::query::__query_compute::normalize_projection_ty
  20: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::normalize_projection_ty<'tcx>>::compute
  21: rustc::ty::context::tls::with_context
  22: rustc::dep_graph::graph::DepGraph::with_task_impl
  23: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start
  24: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  25: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  26: <rustc::traits::query::normalize::QueryNormalizer<'cx, 'gcx, 'tcx> as rustc::ty::fold::TypeFolder<'gcx, 'tcx>>::fold_ty
  27: rustc::traits::query::normalize::<impl rustc::infer::at::At<'cx, 'gcx, 'tcx>>::normalize
  28: rustc::ty::context::tls::with_related_context
  29: rustc::infer::InferCtxtBuilder::enter
  30: rustc_traits::normalize_erasing_regions::normalize_ty_after_erasing_regions
  31: rustc::ty::query::__query_compute::normalize_ty_after_erasing_regions
  32: rustc::ty::query::<impl rustc::ty::query::config::QueryAccessors<'tcx> for rustc::ty::query::queries::normalize_ty_after_erasing_regions<'tcx>>::compute
  33: rustc::ty::context::tls::with_context
  34: rustc::dep_graph::graph::DepGraph::with_task_impl
  35: <rustc::ty::query::plumbing::JobOwner<'a, 'tcx, Q>>::start
  36: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::force_query_with_job
  37: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::get_query
  38: <rustc::traits::query::normalize_erasing_regions::NormalizeAfterErasingRegionsFolder<'cx, 'tcx> as rustc::ty::fold::TypeFolder<'tcx, 'tcx>>::fold_ty
  39: <smallvec::SmallVec<A> as core::iter::traits::FromIterator<<A as smallvec::Array>::Item>>::from_iter
  40: rustc::ty::fold::TypeFoldable::fold_with
  41: rustc::traits::query::normalize_erasing_regions::<impl rustc::ty::context::TyCtxt<'cx, 'tcx, 'tcx>>::normalize_erasing_late_bound_regions
  42: rustc_codegen_ssa::mir::block::<impl rustc_codegen_ssa::mir::FunctionCx<'a, 'tcx, Bx>>::codegen_terminator
  43: rustc_codegen_ssa::mir::codegen_mir
  44: rustc_codegen_ssa::base::codegen_instance
  45: rustc_codegen_ssa::mono_item::MonoItemExt::define
  46: rustc_codegen_llvm::base::compile_codegen_unit::module_codegen
  47: rustc::dep_graph::graph::DepGraph::with_task
  48: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::ExtraBackendMethods>::compile_codegen_unit
  49: rustc_codegen_ssa::base::codegen_crate
  50: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_utils::codegen_backend::CodegenBackend>::codegen_crate
  51: rustc::util::common::time
  52: rustc_driver::driver::phase_4_codegen
  53: rustc_driver::driver::compile_input::{{closure}}
  54: rustc::ty::context::tls::enter_context
  55: <std::thread::local::LocalKey<T>>::with
  56: rustc::ty::context::TyCtxt::create_and_enter
  57: rustc_driver::driver::compile_input
  58: rustc_driver::run_compiler_with_pool
  59: <scoped_tls::ScopedKey<T>>::set
  60: rustc_driver::run_compiler
  61: <scoped_tls::ScopedKey<T>>::set
  62: syntax::with_globals
  63: std::panicking::try::do_call
  64: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  65: rustc_driver::run
  66: std::panicking::try::do_call
  67: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  68: rls::build::rustc::rustc
  69: <rls::build::cargo::RlsExecutor as cargo::core::compiler::Executor>::exec
  70: cargo::core::compiler::Executor::exec_and_capture_output
  71: cargo::core::compiler::rustc::{{closure}}
  72: <F as cargo::core::compiler::job::FnBox<A, R>>::call_box
  73: <F as cargo::core::compiler::job::FnBox<A, R>>::call_box
  74: <F as cargo::core::compiler::job::FnBox<A, R>>::call_box
  75: cargo::core::compiler::job::Job::run
  76: crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}
query stack during panic:
end of query stack

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (0c999ed13 2018-12-03) running on x86_64-unknown-linux-gnu
```

**Comment by 0x7CFE** [comment]
Oops, wrong repo. Sorry. Moved  this bug to https://github.com/rust-lang/rls/issues/1166
