### ISSUE TITLE
Cannot install locally built extension npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by angusgraham** [rust-lang/rls-vscode#525]
I was having a problem getting rls to run, so it was suggested to try building and installing a local copy.
So I followed the instructions at https://github.com/rust-lang/rls-vscode/blob/master/contributing.md to install node/npm and built it.
I'm able to debug the extension via the debugger in a new VSCode instance, but when I try to install it I see this:
```
PS C:\Users\agrah\projects\githubrepos\rls-vscode> npm run installDevExtension

> rust@0.5.3 installDevExtension C:\Users\agrah\projects\githubrepos\rls-vscode
> npm install && ./node_modules/.bin/vsce package -o ./out/rls-vscode-dev.vsix && code --install-extension ./out/rls-vscode-dev.vsix


> rust@0.5.3 postinstall C:\Users\agrah\projects\githubrepos\rls-vscode
> node ./node_modules/vscode/bin/install

Detected VS Code engine version: ^1.24.0
Found minimal version that qualifies engine range: 1.24.0
Fetching vscode.d.ts from: https://raw.githubusercontent.com/Microsoft/vscode/6a6e02cef0f2122ee1469765b704faf5d0e0d859/src/vs/vscode.d.ts
vscode.d.ts successfully installed!

audited 1080 packages in 3.26s
found 0 vulnerabilities

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rust@0.5.3 installDevExtension: `npm install && ./node_modules/.bin/vsce package -o ./out/rls-vscode-dev.vsix && code --install-extension ./out/rls-vscode-dev.vsix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rust@0.5.3 installDevExtension script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\agrah\AppData\Roaming\npm-cache\_logs\2019-03-10T22_48_17_801Z-debug.log
```

**Comment by angusgraham** [comment]
log:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'installDevExtension' ]
2 info using npm@6.4.1
3 info using node@v10.15.3
4 verbose run-script [ 'preinstallDevExtension',
4 verbose run-script   'installDevExtension',
4 verbose run-script   'postinstallDevExtension' ]
5 info lifecycle rust@0.5.3~preinstallDevExtension: rust@0.5.3
6 info lifecycle rust@0.5.3~installDevExtension: rust@0.5.3
7 verbose lifecycle rust@0.5.3~installDevExtension: unsafe-perm in lifecycle true
8 verbose lifecycle rust@0.5.3~installDevExtension: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\agrah\projects\githubrepos\rls-vscode\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\dotnet\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Git\cmd;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\nodejs\;C:\Users\agrah\.cargo\bin;C:\Users\agrah\AppData\Local\Microsoft\WindowsApps;;C:\Program Files\Microsoft VS Code\bin;C:\Users\agrah\AppData\Roaming\npm
9 verbose lifecycle rust@0.5.3~installDevExtension: CWD: C:\Users\agrah\projects\githubrepos\rls-vscode
10 silly lifecycle rust@0.5.3~installDevExtension: Args: [ '/d /s /c',
10 silly lifecycle   'npm install && ./node_modules/.bin/vsce package -o ./out/rls-vscode-dev.vsix && code --install-extension ./out/rls-vscode-dev.vsix' ]
11 silly lifecycle rust@0.5.3~installDevExtension: Returned: code: 1  signal: null
12 info lifecycle rust@0.5.3~installDevExtension: Failed to exec installDevExtension script
13 verbose stack Error: rust@0.5.3 installDevExtension: `npm install && ./node_modules/.bin/vsce package -o ./out/rls-vscode-dev.vsix && code --install-extension ./out/rls-vscode-dev.vsix`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid rust@0.5.3
15 verbose cwd C:\Users\agrah\projects\githubrepos\rls-vscode
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "installDevExtension"
18 verbose node v10.15.3
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error rust@0.5.3 installDevExtension: `npm install && ./node_modules/.bin/vsce package -o ./out/rls-vscode-dev.vsix && code --install-extension ./out/rls-vscode-dev.vsix`
22 error Exit status 1
23 error Failed at the rust@0.5.3 installDevExtension script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Xanewok** [comment]
@angusgraham do you have the same problem with the most recent `master` branch?
