### ISSUE TITLE
Extension crashes after some time; formatter and linting fail to work.

### ISSUE THREAD

**Issue by nemosupremo** [rust-lang/rls-vscode#583]
I'm not quite sure how to reproduce, but after working for sometime with rls-vscode extension it will fail to function, and formatting/build errors becomes unavailable. The only thing that seems to fix it is opening/closing the workspace. 

The only thing I can find in the log:
```
[2019-04-29 11:10:41.102] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 11:10:48.325] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 11:10:56.099] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 11:11:27.224] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 11:11:31.036] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 11:16:30.276] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 11:16:55.862] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 11:17:03.158] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:20:130)
[2019-04-29 11:54:24.350] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 12:06:10.700] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 12:27:41.602] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 12:36:35.193] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 17:15:24.636] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 19:55:31.187] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-29 19:57:59.581] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-30 10:06:56.922] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)
[2019-04-30 10:06:58.554] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)
[2019-04-30 10:07:01.997] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)
[2019-04-30 10:26:02.391] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)
[2019-04-30 10:26:28.822] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)
[2019-04-30 11:36:47.417] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)
[2019-04-30 11:38:52.415] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)
[2019-04-30 11:38:55.408] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)
[2019-04-30 11:38:58.615] [renderer1] [error] Tree element not found: [object Object]: Error: Tree element not found: [object Object]
    at s.getElementLocation (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:674)
    at s.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:91:14)
    at j.isCollapsed (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:940:572)
    at B.revealMarkersForCurrentActiveEditor (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:237)
    at B.autoReveal (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5301:94)
    at B.onActiveEditorChanged (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5298:531)
    at B._register.e (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:5297:572)
    at d.fire (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:75:436)
    at setTimeout (file:///Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:71:973)
[2019-04-30 11:39:40.490] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-30 11:40:15.539] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:20:130)
[2019-04-30 11:41:44.650] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:15:105)
[2019-04-30 11:41:45.004] [renderer1] [error] Cannot read property 'value' of undefined: TypeError: Cannot read property 'value' of undefined
	at SignatureHelpProvider.hoverToSignatureHelp (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:75:41)
	at provideSignatureHelp.provideHover.then.hover (/Users/nimi/.vscode/extensions/rust-lang.rust-0.6.1/out/providers/signatureHelpProvider.js:20:130)

```

**Comment by nemosupremo** [comment]
Looks like this issue was caused by the fact my vs-code workspace was using relative paths instead of absolute paths.

**Comment by Ciantic** [comment]
What do you mean? How did you fix this? I get bunch of these also:

```
TypeError: Cannot read property 'value' of undefined
 at SignatureHelpProvider.hoverToSignatureHelp
... signatureHelpProvider.js:15:105
```

And auto-completion does not work, or maybe it just isn't really good?
