### ISSUE TITLE
RLS and Rustup errors on WSL

### ISSUE THREAD

**Issue by tbremer** [rust-lang/rls-vscode#585]
Using Version `0.6.1` I am getting the following errors when opening any `.rs` file:

1. "Couldn't start client Rust Language Server"
1. "Rustup not available. Install from: <link>"

The only setting I have selected is: `Rust-client: Use WSL` which is checked, and that option is only set in the `Remote` settings.

Is there some setting or configuration I am missing?

Here is a complete dump of my console:

```
[Extension Host] debugger listening on port 33089
/C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] Extension 'rust-lang.rust' uses a document selector without scheme. Learn more about this: https://go.microsoft.com/fwlink/?linkid=872305
/C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] running with rustup: rls
/C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] Error: spawn wsl ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
/C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2365 Rustup not available. Install from https://www.rustup.rs/
onDidNotificationChange @ /C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2365
/C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2365 Couldn't start client Rust Language Server
onDidNotificationChange @ /C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:2365
/C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] rejected promise not handled within 1 second: Error: spawn wsl ENOENT
t.log @ /C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:238
/C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:238 [Extension Host] stack trace: Error: spawn wsl ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
t.log @ /C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:238
/C:/Users/tomab/AppData/Local/Programs/Microsoft VS Code Insiders/resources/app/out/vs/workbench/workbench.main.js:1402   ERR spawn wsl ENOENT: Error: spawn wsl ENOENT
	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
	at onErrorNT (internal/child_process.js:406:16)
	at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by roonie007** [comment]
+1

**Comment by Xanewok** [comment]
We deprecated the WSL support in-extension, please try out the [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) extension. This, together with #612 (to be released in the next version) should fix the issue here.
