### ISSUE TITLE
"RLS Starting" with vscode's workspaces

### ISSUE THREAD

**Issue by not-fl3** [rust-lang/rls-vscode#588]
Hello! 

With the following project configuration the rls is working fine in on of the crates("foo" or "bar", depending on which one was opened first), but "RLS Starting" hangs forever in the second one. Is it a known bug? 

```
mkdir workspaces_test && cd workspaces_test
cat <<EOF > test.code-workspace
{
	"folders": [
		{
			"path": "bar"
		},
		{
			"path": "foo"
		}
	],
	"settings": {}
}
EOF
cargo init --bin foo
cargo init --bin bar
code test.code-workspace
```

Tested on ```rls 1.34.0 (0d6f53e 2019-02-14)``` and ```rls 1.36.0 (5b8e99b 2019-05-01)```

**Comment by zkat** [comment]
Just chiming in -- I can reproduce this on both `nightly` and `beta` as of today, but it works fine if I `rustup default stable`.

**Comment by zkat** [comment]
I managed to figure out how to debug extensions aaaand... it turns out this looks like it's being caused by `ClientWorkspace#registerCommands()` being executed again. My current VS Code version doesn't allow registering multiple commands:

```
rejected promise not handled within 1 second: Error: command 'rls.update' already exists
stack trace: Error: command 'rls.update' already exists
	at d.registerCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:496:447)
	at Object.registerCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:715:422)
	at ClientWorkspace.registerCommands (/Users/zkat/Documents/code/personal/rust/rls-vscode/out/extension.js:221:58)
	at ClientWorkspace.<anonymous> (/Users/zkat/Documents/code/personal/rust/rls-vscode/out/extension.js:203:18)
	at Generator.next (<anonymous>)
	at __awaiter (/Users/zkat/Documents/code/personal/rust/rls-vscode/out/extension.js:7:71)
	at new Promise (<anonymous>)
	at __awaiter (/Users/zkat/Documents/code/personal/rust/rls-vscode/out/extension.js:3:12)
	at ClientWorkspace.start (/Users/zkat/Documents/code/personal/rust/rls-vscode/out/extension.js:161:16)
	at didOpenTextDocument (/Users/zkat/Documents/code/personal/rust/rls-vscode/out/extension.js:61:19)
	at vscode_1.workspace.onDidOpenTextDocument.doc (/Users/zkat/Documents/code/personal/rust/rls-vscode/out/extension.js:26:57)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:720)
	at define.constructor._toDispose._documentsAndEditors.onDidAddDocuments.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:523:151)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:720)
	at u.$acceptDocumentsAndEditorsDelta (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:527:343)
	at d._doInvokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643:1006)
	at d._invokeHandler (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:643:698)
	at d._receiveRequest (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:346)
	at d._receiveOneMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:641:141)
	at define.constructor._protocol.onMessage.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:639:400)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:720)
	at a (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:176:551)
	at e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:176:597)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:720)
	at n.constructor.e.onMessage.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:747:721)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:720)
	at a (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:176:551)
	at e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:176:597)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:720)
	at y._receiveMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:185:451)
	at define.constructor._socketDisposables.push._socketReader.onMessage.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:182:756)
	at u.fire (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:47:720)
	at f.acceptChunk (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:179:344)
	at define.constructor._register._socket.onData.e (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:178:688)
	at Socket.t (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:948)
	at Socket.emit (events.js:182:13)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:264:11)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
```

I don't know what the right solution for this is, but I'm going to try and look into what kind of refactoring is needed to pull this out of each instantiation.

**Comment by zkat** [comment]
@not-fl3 I still have to do some work and refactoring on it before it's 100% there, but if you want to get this bit working in the process, you can just clone https://github.com/zkat/rls-vscode/commit/6e5cae8a456817b7b5b75fd46935d8d86486a363 and run `npm i && npm run installDevExtension`.

**Comment by zkat** [comment]
https://github.com/rust-lang/rls-vscode/pull/601 is a thing now. Cheers.
