### ISSUE TITLE
"Rustup not available" (but it is)

### ISSUE THREAD

**Issue by crispinb** [rust-lang/rls-vscode#631]
I'm having the issue previously reported as https://github.com/rust-lang/rls-vscode/issues/577, now closed. The solution/workaround suggested there (setting an explicit rust-client.rustupPath) doesn't work in my case.

Just to reiterate, the problem is rls not starting, with the errors:

> ```
> [Error - 15:01:20] Starting client failed
> Error: spawn rustup ENOENT
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
> 	at onErrorNT (internal/child_process.js:406:16)
> 	at process._tickCallback (internal/process/next_tick.js:63:19)
> ```
> 
> 
> ```
> Rustup not available. Install from https://www.rustup.rs/
> ```
 
I'm using:

rls-vscode version = 0.6.1
rustup version = rustup 1.18.3 (435397f48 2019-05-22)
vscode versions = 1.36.1  & 1.37.0-insider 
wsl2 on Windows Insider build  10.0.18922 
Relevant Vscode settings:
```
"rust-client.updateOnStartup": true,
"rust-client.rustupPath": "/home/username/.cargo/bin/rustup",
"rust-client.useWSL": true,
"rust-client.channel": "stable",
"rust-client.logToFile": true
```

**Comment by crispinb** [comment]
Never mind, it turns out the `rust-client.useWSL` setting conflicts with the VS Code Remote WSL extension, which I am using (https://github.com/rust-lang/rls-vscode/issues/610).
