### ISSUE TITLE
Constantly receiving "The Rust Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted"

### ISSUE THREAD

**Issue by CodingBeagle** [rust-lang/rls-vscode#737]
System:
- MS Windows 10 Home
- Rust (rls) extension version 0.7.0
- Rust 1.41.0

After upgrading to Rust 1.41.0 (I did not have this issue at any point before), I am now constantly receiving the following error in Visual Studio Code:

![image](https://user-images.githubusercontent.com/16617155/73595932-f5e4c480-451d-11ea-90e1-06ae8327a69c.png)

With the following error log:

    thread 'request-worker-10' has overflowed its stack
    [Info  - 6:00:28 PM] Connection to server got closed. Server will restart.
    [Error - 6:00:28 PM] Request textDocument/completion failed.
    Error: Connection got disposed.
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:57:35)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2036:42)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\main.js:127:15)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2023:18)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at StreamMessageReader.fireClose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
        at Socket.<anonymous> (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
        at Socket.emit (events.js:205:15)
        at Pipe.<anonymous> (net.js:586:12)

    thread 'request-worker-6' has overflowed its stack
    [Info  - 6:00:28 PM] Connection to server got closed. Server will restart.
    [Error - 6:00:28 PM] Request textDocument/completion failed.
    Error: Connection got disposed.
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:57:35)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2036:42)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\main.js:127:15)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2023:18)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at StreamMessageWriter.fireClose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:39:27)
        at Socket.<anonymous> (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:58:46)
        at Socket.emit (events.js:200:13)
        at Pipe.<anonymous> (net.js:586:12)
    [Error - 6:00:28 PM] Request textDocument/documentSymbol failed.
    Error: Connection got disposed.
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:57:35)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2036:42)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\main.js:127:15)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2023:18)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at StreamMessageWriter.fireClose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:39:27)
        at Socket.<anonymous> (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:58:46)
        at Socket.emit (events.js:200:13)
        at Pipe.<anonymous> (net.js:586:12)

    thread 'request-worker-2' has overflowed its stack
    [Info  - 6:00:29 PM] Connection to server got closed. Server will restart.
    [Error - 6:00:29 PM] Request textDocument/completion failed.
    Error: Connection got disposed.
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:57:35)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2036:42)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\main.js:127:15)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2023:18)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at StreamMessageWriter.fireClose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:39:27)
        at Socket.<anonymous> (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:58:46)
        at Socket.emit (events.js:200:13)
        at Pipe.<anonymous> (net.js:586:12)

    thread 'request-worker-5' has overflowed its stack
    [Info  - 6:00:29 PM] Connection to server got closed. Server will restart.
    [Error - 6:00:29 PM] Request textDocument/completion failed.
    Error: Connection got disposed.
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:57:35)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2036:42)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\main.js:127:15)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2023:18)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at StreamMessageWriter.fireClose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:39:27)
        at Socket.<anonymous> (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageWriter.js:58:46)
        at Socket.emit (events.js:200:13)
        at Pipe.<anonymous> (net.js:586:12)

    thread 'request-worker-4' has overflowed its stack
    [Error - 6:00:29 PM] Connection to server got closed. Server will not be restarted.
    [Error - 6:00:29 PM] Request textDocument/completion failed.
    Error: Connection got disposed.
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:876:25)
        at Object.dispose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:57:35)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2036:42)
        at LanguageClient.handleConnectionClosed (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\main.js:127:15)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-languageclient\lib\client.js:2023:18)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at closeHandler (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\main.js:226:26)
        at CallbackList.invoke (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:62:39)
        at Emitter.fire (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\events.js:120:36)
        at StreamMessageReader.fireClose (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
        at Socket.<anonymous> (c:\Users\****\.vscode\extensions\rust-lang.rust-0.7.0\node_modules\vscode-jsonrpc\lib\messageReader.js:151:46)
        at Socket.emit (events.js:205:15)
        at Pipe.<anonymous> (net.js:586:12)

**Comment by jannickj** [comment]
I had the same problem it got fixed by updating vscode / rls plugin.

**Comment by ankitbko** [comment]
Facing same problem. However I am running on wsl2.

```
```

**Comment by pYtoner** [comment]
I had the same issue. I then tried to run `rls` on its own:
```user$ rls
error: 'rls' is not installed for the toolchain 'stable-x86_64-apple-darwin'
To install, run `rustup component add rls --toolchain stable-x86_64-apple-darwin`
```
So then I ran that and now its working.
