### ISSUE TITLE
RLS and Rustup errors on Code-Server

### ISSUE THREAD

**Issue by nadrojisk** [rust-lang/rls-vscode#814]
Version: 0.7.8

I am getting the following errors when opening any .rs file:

1.   "Couldn't start client Rust Language Server"
2.   "Rustup not available. Install from: "

I've already ran rustup on the system and installed the default components. I see there are a lot of different issues that have this but I was not able to correct my problem by following their suggestions. Additionally .cargo/bin is apart of my path as well.

**Comment by crlsktr** [comment]
I'm experiencing the same issue. I believe it is a subtle difference in how the extension loads the bash environment and how a terminal is used to load the environment. Normally when you open a terminal bash will load your .bashrc file and .profile. Rustup modifies .bashrc to add .cargo/bin to the path.
When you open the output tab and select `Rust Language Server` from the dropdown do you see the following output?
```
[Error - 10:14:32 PM] Starting client failed
Error: Command failed: rustup toolchain list
/bin/sh: rustup: command not found

	at ChildProcess.exithandler (child_process.js:308:12)
	at ChildProcess.emit (events.js:203:13)
	at maybeClose (internal/child_process.js:1021:16)
	at Socket.<anonymous> (internal/child_process.js:430:11)
	at Socket.emit (events.js:203:13)
	at Pipe.<anonymous> (net.js:588:12)
```

If you do (or something pretty similar) you can trick the extension into spitting out the path that it sees by changing the path to rustup

settings.json (vscode)
```
"rust-client.rustupPath": "echo $PATH",
```

Then it'll sort of vomit out the path and I can't see .cargo/bin as part of the path in that context.

**Comment by crlsktr** [comment]
workaround: you can get it working by adding the fully qualified path to your settings.json
```
"rust-client.rustupPath": "/home/[user]/.cargo/bin/rustup",
```
